name: Deploy Theme
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1.6.6
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          theme-name: casper-custom
#          exclude: "gulpfile.js *dist/*"
#          file: # Path to a built zip file. If this is included, the exclude and theme-name options are ignored
#          working-directory: # A custom directory to zip when a theme is in a subdirectory, e.g. packages/my-theme
